### ISSUE TITLE
Local copy of train dataset

### ISSUE THREAD

**Issue by LinminWang** [scaomath/kaggle-jane-street#1]
Hello, kudos to the great work! I am attempting to recreate some of your work as part of the self-learning process but the data set used in the modeling expired. Could you send me a copy of the train.csv and test.csv, if you happen to have local copies of them? Many thanks!

**Comment by scaomath** [comment]
Sorry I do not have a local copy right now. I think according to the Jane Street's term, it is not legal to publicly share them either.

**Comment by LinminWang** [comment]
OK, I did not know that. Thanks for the heads-up!
